### ISSUE TITLE
Can't set send tx due to gas price

### ISSUE THREAD

**Issue by fdnahrwold** [ConsenSys/icebox#11]
I am running icebox on an airgapped RPi2 using Iceweasel.  Wallet restores and generates txs just fine, but when trying to broadcast the transaction via etherscan.io i receive the error

`Error! Unable to broadcast Tx : { "id": 1, "jsonrpc": "2.0", "error": { "code": -32603, "message": "Insufficient funds for gas * price + value" } }`

I have tried the default setting in icebox and all manner of other variations.  Using geth console I get 

`ReferenceError 'tx' is not defined
`
And sendtx.html just seems to roll over and and do nothing for me trying to broadcast using Chrome on Windows 10

I am trying to send a test amount of between 1 and 3 ether (there are only 3 ether in the icebox created address I am using) to verify I have control of the address before moving a substantial amount.  Is the default gas price insufficient for such a small amount, do I need to find a way to manually calculate it, or is something else broken?

**Comment by christianlundkvist** [comment]
Gasprice and gaslimit has been added into the UI now.
