### ISSUE TITLE
QR code of 'Signed Transaction' to be displayed on HTML page itself

### ISSUE THREAD

**Issue by dmaaa** [ConsenSys/icebox#15]
Dears, 
Thank you for bringing Icebox to the market.  This tool is so unique, simple and secure; Such a brilliant idea ! 

Despite my limited IT knowledge, I believe there is a strong use case to include on the HTML page the feature : 

> Display QR code for the 'Signed Transaction'.

95% of people own an 'old phone' that could be turned into a 'never connected to internet anymore' device.  Sharing the 'Signed Transaction' to the 2nd device via QR code would offer a lot of convenience and security.  
On the other side, I'm trying to convince Etherscan to develop a simple Mobile App allowing to snap QR code of 'Signed Transactions'. 

Once on the market, the combo (Icebox + Etherscan) would be powerful.
Spending from Icebox wallet would be a matter of seconds allowing each and every person to become its own banker with great ease of use.  

I currently have to load the Icebox HTML on an android phone, via USB on OTG port.. but I need so many third party apps on my 2 phones, to copy-paste the HEX transaction into QR code scanner, then snap QR code, then paste into Etherscan..  that's a long process, with the risk of typing errors while copy-pasting multiple times on the 2 phones. 

Thank you;
Diego

**Comment by zmitton** [comment]
@dmaaa I agree with this. But we can do even one better. If the QR code embeds a http request to etherscan's API, then simply reading it from *any* QR app will auto-send the transaction

<img width="966" alt="screen shot 2017-05-03 at 2 30 56 pm" src="https://cloud.githubusercontent.com/assets/6954889/25679653/077a8eb0-301c-11e7-8aa7-d4248402b73c.png">

**Comment by zmitton** [comment]
Fixed by PR #24

**Comment by christianlundkvist** [comment]
Fixed as @zmitton stated above :)
