### ISSUE TITLE
Not able to sign transaction

### ISSUE THREAD

**Issue by rverbee** [ConsenSys/icebox#18]
I kept getting an error in the javascript console when attempting to sign a transaction in version 0.2.2

something about a null object or wrong type. Can't remember fully. Will update when I am back by my offline computer.

**Comment by Canalytic** [comment]
I am also trying to send a raw transaction.  With the tx I get from the QR code, I get this error:

json: cannot unmarshal object into Go value of type string
    at web3.js:3119:20
    at web3.js:6023:15
    at web3.js:4995:36
    at <anonymous>:1:1

coming from eth.sendRawTransaction()

**Comment by Canalytic** [comment]
The tx that the QR code generates are we supposed to paste all of it?
