### ISSUE TITLE
Send tx functionality with sendtx.html did not work

### ISSUE THREAD

**Issue by MeherRoy** [ConsenSys/icebox#2]
Hello,

I tried Icebox. Works like a charm (mostly). The sendtx.html file did not work correctly. It displayed transaction sent but the network did not pick it up. I am attaching a screenshot for reference.

Thank you for the help.
[ICEBOX - send tx issue.pdf](https://github.com/ConsenSys/icebox/files/109764/ICEBOX.-.send.tx.issue.pdf)

**Comment by kumavis** [comment]
heres the screenshot from the pdf
![image](https://cloud.githubusercontent.com/assets/1474978/12683008/695fd99e-c66b-11e5-8ce9-6b564ee17666.png)

**Comment by kumavis** [comment]
maybe theres an error in the terminal we missed

**Comment by eterps** [comment]
I have the the same problem, I get the following error in the console:

```
OPTIONS http://localhost:8545/ net::ERR_CONNECTION_REFUSED
```

Tested on Mac & Linux.

**Comment by eterps** [comment]
Hmmm, I suppose it wants to RPC to geth, will check that.

**Comment by eterps** [comment]
Using `geth --rpc --rpccorsdomain localhost` didn't work either. I used `geth console` instead, the README might need some more info on this.

**Comment by christianlundkvist** [comment]
@MeherRoy @kumavis @eterps 

The sendtx.html requires a locally running node. @badmofo was kind enough to create this send-tx website which works well and I advise everyone to use:

https://badmofo.github.io/ethsend/
