### ISSUE TITLE
add capital/lowercase checksuming

### ISSUE THREAD

**Issue by zmitton** [ConsenSys/icebox#23]
Might be useful here since there is some difficulty moving things from an air gapped device

**Comment by zmitton** [comment]
Also, might be possible to add the ability to generate a QR code here using a library (instead of requiring workflow app). If the signed transaction could be automatically embedded in an infura url (although it would have to be `GET` not `POST`), then any QR app from another device could read it, and that would trigger the transaction being sent (because those QR apps automatically try to take you to a web page when they read a url)

**Comment by zmitton** [comment]
Finally adding some mobile responsiveness would make it much easier for use.

@christianlundkvist  Would you be open to these features if I made a PR? Do they make sense to add?

**Comment by christianlundkvist** [comment]
Would love a PR thanks!

* QR: awesome but I would also like to keep the ability to copy the tx data manually as we do now. 
* Reponsiveness: yes, totally needed
* Checksum: I want to keep backwards compatibility, so could imagine accepting all lowercase, all uppercase or correct checksum.

**Comment by zmitton** [comment]
yes agree with all of that. The QR code is the only thing that isnt perfect. it shows up big when I simulate mobile, but on my actual device its small. It seems to scan just fine. So all of the above is added by PR #24
