### ISSUE TITLE
Gas price functionality is confusing

### ISSUE THREAD

**Issue by MeherRoy** [ConsenSys/icebox#3]
Hello,

I am using Icebox to send transactions, and am confused what the Gas Price field actually means. Currently, it contains the value 100,000,000,000. What are the units exactly?

What value should it have in order to empty an account completely?

Any help would be appreciated.

**Comment by hairychris** [comment]
Gas price controls how quickly the network will process your transaction, a higher gas price results in quicker processing. Please see https://ethereum.gitbooks.io/frontier-guide/content/costs.html for more info. A sensible value can be found at http://ether.fund/tool/gas-price

**Comment by christianlundkvist** [comment]
@MeherRoy Having a "send-all" functionality is something that I want to add to icebox.

**Comment by christianlundkvist** [comment]
Added Issue https://github.com/ConsenSys/icebox/issues/7
