### ISSUE TITLE
False Positive "Transaction Sent!" sendtx.html message

### ISSUE THREAD

**Issue by robertandrewsmith** [ConsenSys/icebox#9]
sendtx.html returns  "Transaction Sent!" when in fact, the transaction is NOT sent.  The same signed transaction in web3.eth.sendRawTransaction(tx) tells me "Insufficient funds for gas * price + value".

It really would be helpful to have the correct message appear after sending a raw transaction.

Can sendtx.html check a blockchain account balance before it sends? Seems to me, sendtx.html is used on computers with an internet connection.....

**Comment by christianlundkvist** [comment]
@robertandrewsmith: Try this page instead: http://badmofo.github.io/ethsend/
